'use strict';

const reunioesData = [
  {
    nome: 'Grupo Nova História — Osasco',
    horario: '18h00 - 19h30',
    endereco: 'Av. Thereza Ana Cecon Breda, 1896',
    tipo: 'Reunião aberta',
    dist: '1,2 KM DE VOCÊ',
    dia: '16',
    mes: 'ABR',
    diasem: 'QUI',
    cidade: 'Osasco — SP',
    contato: '(11) 99571-6942',
    descricao: 'Grupo voltado para iniciantes e veteranos. Ambiente acolhedor, café e água disponíveis. Chegue 10 minutos antes para se ambientar.',
    lat: -23.5327,
    lng: -46.7919,
  },
  {
    nome: 'Grupo Recomeço — São Paulo',
    horario: '19h00 - 20h30',
    endereco: 'Rua da Consolação, 451',
    tipo: 'Reunião aberta',
    dist: '3,5 KM DE VOCÊ',
    dia: '17',
    mes: 'ABR',
    diasem: 'SEX',
    cidade: 'São Paulo — SP',
    contato: '(11) 99571-6942',
    descricao: 'Reunião semanal com partilha aberta. Todos são bem-vindos, não é necessário avisar com antecedência.',
    lat: -23.5476,
    lng: -46.6457,
  },
  {
    nome: 'Grupo Esperança — Santo André',
    horario: '20h00 - 21h00',
    endereco: 'Av. Industrial, 2000',
    tipo: 'Reunião fechada',
    dist: '8,1 KM DE VOCÊ',
    dia: '18',
    mes: 'ABR',
    diasem: 'SAB',
    cidade: 'Santo André — SP',
    contato: '(11) 94321-0000',
    descricao: 'Reunião fechada exclusiva para membros em recuperação. Para participar pela primeira vez, entre em contato antes.',
    lat: -23.6382,
    lng: -46.5393,
  },
  {
    nome: 'Grupo Renascer — Campinas',
    horario: '19h00 - 20h30',
    endereco: 'Rua Barão de Jaguara, 1234',
    tipo: 'Reunião aberta',
    dist: '12,4 KM DE VOCÊ',
    dia: '19',
    mes: 'ABR',
    diasem: 'DOM',
    cidade: 'Campinas — SP',
    contato: '(19) 99876-5432',
    descricao: 'Grupo ativo há mais de 10 anos. Reuniões aos domingos com foco em estudo dos 12 Passos.',
    lat: -22.9034,
    lng: -47.0591,
  },
  {
    nome: 'Grupo Liberdade — Santos',
    horario: '18h30 - 20h00',
    endereco: 'Av. Ana Costa, 555',
    tipo: 'Reunião aberta',
    dist: '18,7 KM DE VOCÊ',
    dia: '20',
    mes: 'ABR',
    diasem: 'SEG',
    cidade: 'Santos — SP',
    contato: '(13) 99765-4321',
    descricao: 'Grupo próximo à praia com ambiente tranquilo. Estacionamento disponível no local.',
    lat: -23.9687,
    lng: -46.3326,
  },
  {
    nome: 'Grupo Horizonte — Guarulhos',
    horario: '20h00 - 21h30',
    endereco: 'Rua Sete de Setembro, 300',
    tipo: 'Reunião fechada',
    dist: '22,1 KM DE VOCÊ',
    dia: '21',
    mes: 'ABR',
    diasem: 'TER',
    cidade: 'Guarulhos — SP',
    contato: '(11) 98765-1234',
    descricao: 'Reunião fechada com foco em prevenção de recaída. Indicada para membros com pelo menos 30 dias de abstinência.',
    lat: -23.4688,
    lng: -46.5286,
  },
];

const videosData = [
  { titulo: '#015 Vício em Jogos e Saúde Pública', thumb: 'assets/images/videoteca/video-01.jpg', canal: 'JA Brasil', views: '2.3K' },
  { titulo: 'Como funcionam as apostas online?', thumb: 'assets/images/videoteca/video-02.jpeg', canal: 'JA Brasil', views: '1.8K' },
  { titulo: 'Os Doze Passos: O caminho para a recuperação', thumb: 'assets/images/videoteca/video-03.jpg', canal: 'JA Brasil', views: '3.1K' },
  { titulo: 'Depoimento: Como parei de jogar', thumb: 'assets/images/videoteca/video-04.jpg', canal: 'JA Brasil', views: '4.7K' },
  { titulo: 'Família e jogo compulsivo: como ajudar', thumb: 'assets/images/videoteca/video-05.jpeg', canal: 'JA Brasil', views: '2.0K' },
  { titulo: 'Autoavaliação: Você é um jogador compulsivo?', thumb: 'assets/images/videoteca/video-06.jpg', canal: 'JA Brasil', views: '5.5K' },
];

const quizPerguntas = [
  'Você já perdeu horas de trabalho da escola devido ao jogo?',
  'Alguma vez o jogo já causou infelicidade na sua vida familiar?',
  'O jogo afetou a sua reputação?',
  'Você já sentiu remorso após jogar?',
  'Alguma vez você já jogou para obter dinheiro para pagar dívidas ou então resolver dificuldades financeiras?',
  'O jogo causou uma diminuição na sua ambição ou eficiência?',
  'Após ter perdido você se sentiu como se necessitasse voltar o mais cedo possível e recuperar as suas perdas?',
  'Após um ganho você sentiu uma forte vontade de voltar e ganhar mais?',
  'Você geralmente jogava até que seu último centavo acabasse?',
  'Você já pediu dinheiro emprestado para financiar seu jogo?',
  'Alguma vez você já vendeu alguma coisa para financiar o jogo?',
  'Você relutava em usar o "dinheiro de jogo" para as despesas normais?',
  'O jogo o tornou descuidado com o seu bem estar e o de sua família?',
  'Alguma vez você já jogou por mais tempo do que planejava?',
  'Alguma vez você já jogou para fugir das preocupações ou problemas?',
  'Alguma vez você já cometeu, ou pensou em cometer um ato ilegal para financiar o jogo?',
  'O jogo fez com que você tivesse dificuldades para dormir?',
  'As discussões, desapontamentos ou frustrações fizeram com que você tivesse vontade de jogar?',
  'Alguma vez você já teve vontade de celebrar alguma boa sorte com algumas horas de jogo?',
  'Alguma vez você já pensou em se auto-destruir como resultado de seu jogo?',
];