# Generated by Django 6.0.6 on 2026-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do grupo')),
                ('horario', models.CharField(help_text='Ex: 19h00 - 20h30', max_length=50, verbose_name='Horário')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('tipo', models.CharField(choices=[('aberta', 'Reunião aberta'), ('fechada', 'Reunião fechada')], default='aberta', max_length=10, verbose_name='Tipo')),
                ('contato', models.CharField(blank=True, max_length=30, verbose_name='Contato (telefone)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dia', models.CharField(help_text='Ex: 16', max_length=2, verbose_name='Dia')),
                ('mes', models.CharField(help_text='Ex: ABR', max_length=3, verbose_name='Mês')),
                ('diasem', models.CharField(help_text='Ex: QUI', max_length=3, verbose_name='Dia da semana')),
                ('dist', models.CharField(blank=True, help_text='Ex: 1,2 KM DE VOCÊ', max_length=50, verbose_name='Distância (texto)')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['dia', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('thumb', models.CharField(help_text='Ex: assets/images/videoteca/video-01.jpg', max_length=300, verbose_name='Caminho da thumbnail')),
                ('canal', models.CharField(default='JA Brasil', max_length=100, verbose_name='Canal')),
                ('views', models.CharField(default='0', help_text='Ex: 2.3K', max_length=20, verbose_name='Visualizações (texto)')),
                ('url', models.URLField(blank=True, verbose_name='URL do vídeo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['ordem'],
            },
        ),
    ]
