-- Flyway migration: create table for news articles
CREATE TABLE IF NOT EXISTS news_article (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(1000),
  description VARCHAR(4000),
  url VARCHAR(2000) UNIQUE,
  image_url VARCHAR(2000),
  source VARCHAR(500),
  published_at TIMESTAMP WITH TIME ZONE,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_published_at ON news_article(published_at);
