spring.application.name=ads3
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/sitepsiads32026
spring.datasource.username=postgres
spring.datasource.password=sitepsi123ads3

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=7f3c9a2b1d6e4f88a91c2d7e5b3c9f10a6d4e8b7c2a9d1f6e5b8c3a2d7f9e1b4