spring.application.name=ads3
server.port=${PORT:8081}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ads3}
spring.datasource.username=${DATABASE_USER:ads3user}
spring.datasource.password=${DATABASE_PASSWORD:ads3user}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
newsapi.key=0b34dea073854648889d401ecd4dcc5e